# Site settings
title: Noorim's Graduation Project
email: T.noorim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  한성대학교 멀티미디어 공학과 졸업프로젝트 팀 Noorim 입니다.
  지도교수님은 권정혁, 팀원은 1291011 김태리,  1291037 이지아, 
  1291044 정유진 입니다.
baseurl: "http://noorim.github.io" # the subpath of your site, e.g. /blog/
url: "http://noorim.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  noorim

# Build settings
markdown: kramdown
