# Site settings
title: Noorim
header-img: img/home-bg.jpg
email: 
description: "HSU Multi Graduation Procjet Team Blog"
baseurl: 
url: "http://noorim.github.io"
twitter_username: 
github_username: noorim
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
